### ISSUE TITLE
type error on deploy

### ISSUE THREAD

**Issue by jimscarver** [tgrospic/rnode-client-js#42] opened 2023-05-04 23:11 UTC
Invalid message "data": 18,203,3,109,97,116,99,104,32,91,34,104,101,108,108,111,32,119,111,114,108,100,34,93,32,123
,...
86,254,48,56,1,64,192,150,177,2,80,229,214,112 must be a valid string.

![image](https://user-images.githubusercontent.com/3037201/236349173-de92f96a-9086-4380-9949-06fdffb6b811.png)

**Comment by tgrospic** [comment] 2023-05-22 16:45
Hi Jim! Sorry for the slow response.

Can you please paste the whole Rholang code so I can try to reproduce the error you see.

Did you see network request `/deploy` is executed in the browser?

Do you see the same error on test net?

I'm not sure if the source of the error is client side or more likely coming from the server not able to deserialize the deploy message.

**Comment by jimscarver** [comment] 2023-05-24 17:06
all deploys fail
![image](https://github.com/tgrospic/rnode-client-js/assets/3037201/e20ddf07-e2ed-421a-90fe-ddf1f5fe52fe)
testnet is not running but I get the same error on rhobot.

**Comment by tgrospic** [comment] 2023-06-01 21:31
I found the problem. It was not visible when signing with the private key, but only with Metamask.

Metamask (ETH) method `personal_sign` changed and accepts hex string instead of array of bytes.

The issue is fixed in https://github.com/tgrospic/rnode-client-js/commit/457beb2c9e2f5a747ecf625191477b598e53f53d commit and deployed with CI.

Deploy and signing with Metamask should work now.

**Closed** 2023-06-10 11:52 UTC
